/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as LicensingRouteImport } from './routes/licensing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as RevisionsRouteImport } from './routes/revisions'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as CertificatesLicenceRouteImport } from './routes/certificates/licence'
import { Route as CertificatesOwnershipRouteImport } from './routes/certificates/ownership'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensingRoute = LicensingRouteImport.update({
  id: '/licensing',
  path: '/licensing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisionsRoute = RevisionsRouteImport.update({
  id: '/revisions',
  path: '/revisions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesLicenceRoute = CertificatesLicenceRouteImport.update({
  id: '/certificates/licence',
  path: '/certificates/licence',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesOwnershipRoute = CertificatesOwnershipRouteImport.update({
  id: '/certificates/ownership',
  path: '/certificates/ownership',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/delivery': typeof DeliveryRoute
  '/licensing': typeof LicensingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/revisions': typeof RevisionsRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/certificates/licence': typeof CertificatesLicenceRoute
  '/certificates/ownership': typeof CertificatesOwnershipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/delivery': typeof DeliveryRoute
  '/licensing': typeof LicensingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/revisions': typeof RevisionsRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/certificates/licence': typeof CertificatesLicenceRoute
  '/certificates/ownership': typeof CertificatesOwnershipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/delivery': typeof DeliveryRoute
  '/licensing': typeof LicensingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/revisions': typeof RevisionsRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/certificates/licence': typeof CertificatesLicenceRoute
  '/certificates/ownership': typeof CertificatesOwnershipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookies'
    | '/delivery'
    | '/licensing'
    | '/privacy'
    | '/refunds'
    | '/revisions'
    | '/terms'
    | '/thank-you'
    | '/certificates/licence'
    | '/certificates/ownership'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/delivery'
    | '/licensing'
    | '/privacy'
    | '/refunds'
    | '/revisions'
    | '/terms'
    | '/thank-you'
    | '/certificates/licence'
    | '/certificates/ownership'
  id:
    | '__root__'
    | '/'
    | '/cookies'
    | '/delivery'
    | '/licensing'
    | '/privacy'
    | '/refunds'
    | '/revisions'
    | '/terms'
    | '/thank-you'
    | '/certificates/licence'
    | '/certificates/ownership'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiesRoute: typeof CookiesRoute
  DeliveryRoute: typeof DeliveryRoute
  LicensingRoute: typeof LicensingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  RevisionsRoute: typeof RevisionsRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  CertificatesLicenceRoute: typeof CertificatesLicenceRoute
  CertificatesOwnershipRoute: typeof CertificatesOwnershipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licensing': {
      id: '/licensing'
      path: '/licensing'
      fullPath: '/licensing'
      preLoaderRoute: typeof LicensingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisions': {
      id: '/revisions'
      path: '/revisions'
      fullPath: '/revisions'
      preLoaderRoute: typeof RevisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/licence': {
      id: '/certificates/licence'
      path: '/certificates/licence'
      fullPath: '/certificates/licence'
      preLoaderRoute: typeof CertificatesLicenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/ownership': {
      id: '/certificates/ownership'
      path: '/certificates/ownership'
      fullPath: '/certificates/ownership'
      preLoaderRoute: typeof CertificatesOwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiesRoute: CookiesRoute,
  DeliveryRoute: DeliveryRoute,
  LicensingRoute: LicensingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  RevisionsRoute: RevisionsRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  CertificatesLicenceRoute: CertificatesLicenceRoute,
  CertificatesOwnershipRoute: CertificatesOwnershipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
